### ISSUE TITLE
Cannot GET / error when navigating to localhost:8080

### ISSUE THREAD

**Issue by gangster** [jaysoo/scalable-frontend-with-redux-saga-jaysoo#1]
Hey Jay, just read the post on organizing redux apps, and found my way here.  Just wanted to give you a heads up.   I cloned the repository and started the app, and when I tried to navigate to http://localhost:8080, I received the error message:

``` text
Cannot GET /
```

Haven't dug too deep into what might be causing it, but figured I'd let you know.    Great post, btw.  Super helpful.

**Comment by jaysoo** [comment]
Thanks @gangster for letting me know. I forgot to push the index.html file with the repo. :)

If you pull from master again it'll work.
